server:
  listen_addr: :9010
  allow_origins:
    - http://localhost:3000
    - http://127.0.0.1:3000

log:
  level: info

mongodb:
  main: mongodb://root:123456@192.168.5.10:27017/mallard?authSource=admin

auth:
  jwt_secret: "change-me-to-a-random-secret"
  access_token_expire_seconds: 900
  refresh_token_expire_seconds: 604800
  cookie_secure: true

tracing_data:
  spans_expire_seconds: 604800
