server_addr: :9010
collector_addr: :9011

allow_origins:
  - http://localhost:5173
  - http://127.0.0.1:5173
collector_allow_origins:
  - http://localhost:5173
  - http://127.0.0.1:5173

log_level: info

mongo_uri: mongodb://root:123456@192.168.5.10:27017/mallard?authSource=admin

jwt_secret: "change-me-to-a-random-secret"
access_ttl: 900
refresh_ttl: 604800
span_ttl: 604800
cookie_secure: false
